# Generated by Django 4.1.1 on 2022-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='entry',
            field=models.CharField(max_length=200),
        ),
    ]
